-- Runs once, on the first container start, against XEPDB1 as SYSDBA.
-- The gvenzl image already created the APP_USER (clyvo) on the PDB and granted
-- the usual quotas. We only add a couple of seed rows so a fresh deploy has
-- something to GET.

ALTER SESSION SET CURRENT_SCHEMA = CLYVO;

-- Hibernate will create the PETS table on first boot (ddl-auto=update), but
-- having an idempotent seed makes manual testing nicer.
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE PETS (
        ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        NAME       VARCHAR2(100) NOT NULL,
        SPECIES    VARCHAR2(50)  NOT NULL,
        BREED      VARCHAR2(80),
        AGE        NUMBER,
        OWNER_NAME VARCHAR2(120) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN  -- ORA-00955: name is already used
            RAISE;
        END IF;
END;
/

MERGE INTO PETS p USING (
    SELECT 'Rex'     AS NAME, 'dog' AS SPECIES, 'Labrador' AS BREED, 4 AS AGE, 'Maria Silva' AS OWNER_NAME FROM dual UNION ALL
    SELECT 'Mia',          'cat',      'Siamese',  3, 'João Souza' FROM dual UNION ALL
    SELECT 'Biscoito',     'rabbit',   NULL,       2, 'Ana Lima'   FROM dual
) s
ON (p.NAME = s.NAME AND p.OWNER_NAME = s.OWNER_NAME)
WHEN NOT MATCHED THEN INSERT (NAME, SPECIES, BREED, AGE, OWNER_NAME)
VALUES (s.NAME, s.SPECIES, s.BREED, s.AGE, s.OWNER_NAME);

COMMIT;
